name = "PowerfulCases"
uuid = "a1b2c3d4-5678-4abc-9def-0123456789ab"
version = "0.2.2"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.10"
