name = "ieee37_opendss"
description = "IEEE 37-bus distribution test feeder (OpenDSS format)"

[credits]
license = "BSD-3-Clause"
authors = ["EPRI"]
maintainers = ["PowerfulCases Contributors"]

[[credits.citations]]
text = "IEEE 37 Node Test Feeder, OpenDSS Test Cases, EPRI Distribution System Simulator"

[[files]]
path = "ieee37.dss"
format = "opendss"
default = true

[[files]]
path = "IEEELineCodes.DSS"
format = "opendss"

[[files]]
path = "IEEE37_BusXY.csv"
format = "csv"
