name = "ACTIVSg2000_singlegen"
description = "ACTIVS 2,000-bus synthetic case with single generator per bus"

[[files]]
path = "ACTIVSg2000_singlegen.raw"
format = "psse_raw"
format_version = "33"
default = true

[[files]]
path = "ACTIVSg2000_singlegen.dyr"
format = "psse_dyr"
default = true
